cd ..
cd ..
make re
clear
echo ***cheeze_maze***
./cub3D cart/valid/cheese_maze.cub
echo ***creepy***
./cub3D cart/valid/creepy.cub
echo ***dungeon***
./cub3D cart/valid/dungeon.cub
echo ***library***
./cub3D cart/valid/library.cub
echo ***matrix***
./cub3D cart/valid/matrix.cub
echo ***sad_face***
./cub3D cart/valid/sad_face.cub
echo ***square_map***
./cub3D cart/valid/square_map.cub
echo ***subjects_map***
./cub3D cart/valid/subject_map.cub
echo ***test_map***
./cub3D cart/valid/test_map.cub
echo ***test_map_hole***
./cub3D cart/valid/test_map_hole.cub
echo ***test_pos_bottom***
./cub3D cart/valid/test_pos_bottom.cub
echo ***test_pos_left**
./cub3D cart/valid/test_pos_left.cub
echo ***test_pos_right***
./cub3D cart/valid/test_pos_right.cub
echo ***test_pos_top***
./cub3D cart/valid/test_pos_top.cub
echo ***test_textures***
./cub3D cart/valid/test_textures.cub
echo ***test_whitespace***
./cub3D cart/valid/test_whitespace.cub
echo ***works***
./cub3D cart/valid/works.cub
